Add 'Quantity' column
gnosaes/umlib pull request #3
Opened 2021-01-23 07:32 UTC by izzatyazam

Add 'Quantity' column in table book and display where needed

2021-01-23 07:40 UTC, juasfan requested changes

2021-01-23 07:40 UTC, juasfan commented on admin/add-book.php
> +                    <input class="form-control" type="text" name="quantity" autocomplete="off" required="required" />
change the type to number

2021-01-23 07:40 UTC, juasfan commented on admin/add-book.php
> +    $query->bindParam(':price', $quantity, PDO::PARAM_STR);
:price here supposed to be :quantity

2021-01-27 04:48 UTC, closed without merging

2021-01-27 04:48 UTC, izzatyazam commented
done